//! Guest-side codec for the RBS1 binary-value ENVELOPE
//! (`contracts/store-net-bytes.json`) — the R2 first-class-bytes wire that
//! carries byte-stream fields across the guest<->host capability seam as raw
//! length-prefixed segments instead of a JSON number-array.
//!
//! Unlike `wire_encode` / `canvas_encode` (opcode streams, gated behind the
//! `wip-binary-protocol` feature), this is ADDITIVE INFRA compiled into the
//! shipped guest unconditionally. It changes NO existing call's default path:
//! `encode_value` only emits an `RBS1` frame when the value actually carries a
//! byte stream — a segment-free value stays byte-for-byte identical to today's
//! raw JSON (the back-compat invariant). The framing is SYMMETRIC: the same
//! codec encodes a guest->host request and decodes a host->guest return.
//!
//! Two layers:
//!   - Framing primitives — [`encode_envelope`] frames a pre-authored JSON
//!     control plane (already holding `{"$b":N}` sentinels) plus its segments
//!     into the wire bytes; [`decode_envelope`] unframes bytes back into the
//!     JSON slice + segment slices. These enforce every fail-closed cap.
//!   - Value walking — [`Value`] + [`encode_value`] hoist every `Value::Bytes`
//!     to a new segment and replace it with `{"$b":N}` in the control plane;
//!     [`decode_value`] revives each sentinel back into `Value::Bytes`. This is
//!     the self-describing, contract-agnostic path (no per-call descriptor).
//!
//! `no_std`, no JSON crate: a compact hand parser/serializer (mirroring
//! `mini_json.rs`) turns the control plane between text and [`Value`]. The magic
//! and caps are the build-time-generated constants — a renamed/removed schema
//! key fails the build, so the guest and host cannot drift.

use alloc::string::String;
use alloc::vec::Vec;
use core::fmt::Write as _;

// MAGIC, PROTOCOL_VERSION, limits::{MAX_SEGMENTS, MAX_SEGMENT_BYTES,
// MAX_ENVELOPE_BYTES, MAX_JSON_BYTES} — generated by build.rs from the schema.
include!(concat!(env!("OUT_DIR"), "/store_net_contract.rs"));

use limits::{MAX_ENVELOPE_BYTES, MAX_JSON_BYTES, MAX_SEGMENTS, MAX_SEGMENT_BYTES};

// Largest exactly-representable integer magnitude in an f64 (2^53). Used for the
// integral-number checks below without `f64::abs`/`fract` (both live in `std`,
// not `core`, so they are unavailable in this `no_std` crate).
const MAX_SAFE_INT_F64: f64 = 9_007_199_254_740_992.0;

/// A fail-closed decode/encode failure. The token strings are the stable
/// `reasons` vocabulary of `contracts/store-net-bytes.json`, shared verbatim
/// with the TS host codec so both agree on one vocabulary.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum Reason {
    /// The leading `u32` is not `MAGIC` (`RBS1`) — wrong protocol, a cross-fed
    /// `RILL`/`RCNV` buffer, or corrupt.
    BadMagic,
    /// A declared length (`jsonLen`, `segCount`, or a `segLen`) overruns the
    /// remaining buffer, OR trailing bytes remain after exactly `segCount`
    /// segments (strict full consumption).
    Truncated,
    /// `jsonLen > MAX_JSON_BYTES`.
    JsonTooBig,
    /// The control-plane bytes are not well-formed JSON after length validation.
    BadJson,
    /// `segCount > MAX_SEGMENTS`.
    TooManySegments,
    /// A `segLen > MAX_SEGMENT_BYTES`.
    SegmentTooBig,
    /// The whole frame's byte length `> MAX_ENVELOPE_BYTES`.
    EnvelopeTooBig,
    /// A `{"$b":N}` sentinel references `N` outside `[0, segCount)`.
    BadSegmentRef,
    /// The reserved key `$b` used wrongly: on DECODE, a `{"$b":...}` object with
    /// a malformed shape (extra keys, or a non-integer / negative value); on
    /// ENCODE, application data using `$b` as an object key in a value that ALSO
    /// carries bytes (so it frames as an envelope, where the peer's `revive` could
    /// not tell the app object from a Bytes sentinel). A `$b` key in a segment
    /// -free value is harmless (plain-JSON path, never revived) and is allowed.
    BadSentinel,
}

impl Reason {
    /// The stable schema `reasons` token for this failure.
    pub fn as_str(self) -> &'static str {
        match self {
            Reason::BadMagic => "bad-magic",
            Reason::Truncated => "truncated",
            Reason::JsonTooBig => "json-too-big",
            Reason::BadJson => "bad-json",
            Reason::TooManySegments => "too-many-segments",
            Reason::SegmentTooBig => "segment-too-big",
            Reason::EnvelopeTooBig => "envelope-too-big",
            Reason::BadSegmentRef => "bad-segment-ref",
            Reason::BadSentinel => "bad-sentinel",
        }
    }
}

/// A parsed JSON control-plane value, extended with a first-class `Bytes`
/// variant for byte-stream fields. Object entries keep source/insertion order
/// so serialization is deterministic (the byte-exact golden lock depends on it).
#[derive(Debug, Clone, PartialEq)]
pub enum Value {
    Null,
    Bool(bool),
    /// A JSON number. Guests build finite values only; non-finite numbers are
    /// not legal JSON and are not emitted by this codec.
    Num(f64),
    Str(String),
    Arr(Vec<Value>),
    Obj(Vec<(String, Value)>),
    /// A byte stream. On [`encode_value`] it is hoisted to a segment and
    /// replaced by `{"$b":N}`; on [`decode_value`] a `{"$b":N}` sentinel is
    /// revived back into this.
    Bytes(Vec<u8>),
}

/// The outcome of [`encode_value`]: either a plain raw-JSON body (no byte
/// streams — the back-compat path, NOT an RBS1 frame) or an RBS1 envelope.
#[derive(Debug, Clone, PartialEq)]
pub enum Encoded {
    /// No byte-stream fields: the raw UTF-8 JSON body, byte-for-byte identical
    /// to today's non-binary wire. MUST NOT be wrapped in an envelope.
    Plain(Vec<u8>),
    /// One or more byte streams: the framed RBS1 envelope.
    Envelope(Vec<u8>),
}

/// A decoded envelope: the JSON control-plane bytes plus each segment's raw
/// bytes, all borrowed from the source buffer (zero-copy). `segments[N]` is what
/// a `{"$b":N}` sentinel resolves to.
#[derive(Debug, PartialEq, Eq)]
pub struct Decoded<'a> {
    /// The UTF-8 JSON control plane (still holding `{"$b":N}` sentinels).
    pub json: &'a [u8],
    /// Segment payloads in emission order (segment index = position).
    pub segments: Vec<&'a [u8]>,
}

// ---- framing primitives ----

/// Frame a pre-authored JSON control plane (already holding `{"$b":N}`
/// sentinels, one per segment, in order) plus its `segments` into RBS1 wire
/// bytes. Enforces every fail-closed cap; on any breach returns `Err(reason)`
/// and emits nothing (whole-frame atomicity).
///
/// This is the primitive the SDK byte wrappers use when they author the control
/// plane by hand; [`encode_value`] is the walking counterpart.
pub fn encode_envelope(json: &str, segments: &[&[u8]]) -> Result<Vec<u8>, Reason> {
    let json_bytes = json.as_bytes();
    if json_bytes.len() > MAX_JSON_BYTES {
        return Err(Reason::JsonTooBig);
    }
    if segments.len() > MAX_SEGMENTS {
        return Err(Reason::TooManySegments);
    }
    // magic(4) + jsonLen(4) + json + segCount(4) + Σ(segLen(4) + seg)
    let mut total = 12usize.saturating_add(json_bytes.len());
    for s in segments {
        if s.len() > MAX_SEGMENT_BYTES {
            return Err(Reason::SegmentTooBig);
        }
        total = total
            .checked_add(4)
            .and_then(|t| t.checked_add(s.len()))
            .ok_or(Reason::EnvelopeTooBig)?;
    }
    if total > MAX_ENVELOPE_BYTES {
        return Err(Reason::EnvelopeTooBig);
    }

    let mut out = Vec::with_capacity(total);
    out.extend_from_slice(&MAGIC.to_le_bytes());
    out.extend_from_slice(&(json_bytes.len() as u32).to_le_bytes());
    out.extend_from_slice(json_bytes);
    out.extend_from_slice(&(segments.len() as u32).to_le_bytes());
    for s in segments {
        out.extend_from_slice(&(s.len() as u32).to_le_bytes());
        out.extend_from_slice(s);
    }
    debug_assert_eq!(out.len(), total);
    Ok(out)
}

/// Unframe RBS1 wire bytes into the JSON control-plane slice + segment slices
/// (zero-copy, borrowing `buf`). Fail-closed: every `u32` length is validated
/// against BOTH its cap AND the remaining buffer before it is used, and the
/// whole buffer MUST be consumed (strict trailing). `Err(Reason::BadMagic)` is
/// the caller's signal to treat `buf` as a plain-JSON body instead.
pub fn decode_envelope(buf: &[u8]) -> Result<Decoded<'_>, Reason> {
    let mut pos = 0usize;
    let magic = read_u32(buf, &mut pos)?;
    if magic != MAGIC {
        return Err(Reason::BadMagic);
    }
    // Whole-frame ceiling, checked once the magic confirmed this is ours.
    if buf.len() > MAX_ENVELOPE_BYTES {
        return Err(Reason::EnvelopeTooBig);
    }

    let json_len = read_u32(buf, &mut pos)? as usize;
    if json_len > MAX_JSON_BYTES {
        return Err(Reason::JsonTooBig);
    }
    let json = read_slice(buf, &mut pos, json_len)?;

    let seg_count = read_u32(buf, &mut pos)? as usize;
    if seg_count > MAX_SEGMENTS {
        return Err(Reason::TooManySegments);
    }
    let mut segments = Vec::with_capacity(seg_count);
    for _ in 0..seg_count {
        let seg_len = read_u32(buf, &mut pos)? as usize;
        if seg_len > MAX_SEGMENT_BYTES {
            return Err(Reason::SegmentTooBig);
        }
        segments.push(read_slice(buf, &mut pos, seg_len)?);
    }
    // Strict full consumption: zero trailing bytes may remain.
    if pos != buf.len() {
        return Err(Reason::Truncated);
    }
    Ok(Decoded { json, segments })
}

#[inline]
fn read_u32(buf: &[u8], pos: &mut usize) -> Result<u32, Reason> {
    let end = pos.checked_add(4).ok_or(Reason::Truncated)?;
    if end > buf.len() {
        return Err(Reason::Truncated);
    }
    let v = u32::from_le_bytes([buf[*pos], buf[*pos + 1], buf[*pos + 2], buf[*pos + 3]]);
    *pos = end;
    Ok(v)
}

#[inline]
fn read_slice<'a>(buf: &'a [u8], pos: &mut usize, len: usize) -> Result<&'a [u8], Reason> {
    let end = pos.checked_add(len).ok_or(Reason::Truncated)?;
    if end > buf.len() {
        return Err(Reason::Truncated);
    }
    let s = &buf[*pos..end];
    *pos = end;
    Ok(s)
}

// ---- value walking (self-describing sentinel hoist / revive) ----

/// Walk `value`, hoisting every [`Value::Bytes`] to a new segment (in walk
/// order) and replacing it with `{"$b":N}` in the JSON control plane, then frame
/// the result. If the value carries NO byte stream, returns [`Encoded::Plain`]
/// (raw JSON, NOT an envelope) — the back-compat invariant. Fail-closed on any
/// cap breach.
pub fn encode_value(value: &Value) -> Result<Encoded, Reason> {
    let mut json = String::new();
    let mut segments: Vec<&[u8]> = Vec::new();
    let mut saw_reserved_key = false;
    write_value(&mut json, value, &mut segments, &mut saw_reserved_key)?;
    if segments.is_empty() {
        // Back-compat: a segment-free value is the plain raw-JSON body, byte-for
        // byte identical to today's wire — never an RBS1 frame. No MAX_JSON_BYTES
        // cap here: the raw-JSON path has none today and this must not change it.
        // A literal `$b` app-key is HARMLESS here: no envelope is produced, so the
        // peer receives plain JSON and never runs `revive` — the key rides through
        // untouched. Only the envelope path below can misread it, so the reserved
        // -key rejection lives there, keeping this path byte-for-byte unchanged.
        Ok(Encoded::Plain(json.into_bytes()))
    } else {
        // An envelope IS produced, so the control plane will be `revive`d by the
        // peer. A literal `$b` app-key would then be indistinguishable from a Bytes
        // sentinel and silently turned into bytes — reject fail-closed. This is the
        // ONLY breakable point, since revive cannot tell the two apart.
        if saw_reserved_key {
            return Err(Reason::BadSentinel);
        }
        Ok(Encoded::Envelope(encode_envelope(&json, &segments)?))
    }
}

fn write_value<'a>(
    out: &mut String,
    value: &'a Value,
    segments: &mut Vec<&'a [u8]>,
    saw_reserved_key: &mut bool,
) -> Result<(), Reason> {
    match value {
        Value::Null => out.push_str("null"),
        Value::Bool(true) => out.push_str("true"),
        Value::Bool(false) => out.push_str("false"),
        Value::Num(n) => write_num(out, *n),
        Value::Str(s) => crate::json_escape(out, s),
        Value::Arr(items) => {
            out.push('[');
            for (i, item) in items.iter().enumerate() {
                if i > 0 {
                    out.push(',');
                }
                write_value(out, item, segments, saw_reserved_key)?;
            }
            out.push(']');
        }
        Value::Obj(entries) => {
            out.push('{');
            for (i, (key, val)) in entries.iter().enumerate() {
                // `$b` is the RESERVED sentinel key. Record that app data used it;
                // `encode_value` rejects only if a byte stream also makes this an
                // envelope (the sole path where the peer's `revive` would misread
                // it as a Bytes sentinel). The encoder's own sentinels are written
                // by the `Bytes` arm below, never here.
                if key == "$b" {
                    *saw_reserved_key = true;
                }
                if i > 0 {
                    out.push(',');
                }
                crate::json_escape(out, key);
                out.push(':');
                write_value(out, val, segments, saw_reserved_key)?;
            }
            out.push('}');
        }
        Value::Bytes(bytes) => {
            // Cap the segment table + each stream as we hoist, so an over-cap
            // value fails closed before any partial frame is built.
            if segments.len() >= MAX_SEGMENTS {
                return Err(Reason::TooManySegments);
            }
            if bytes.len() > MAX_SEGMENT_BYTES {
                return Err(Reason::SegmentTooBig);
            }
            let n = segments.len();
            segments.push(bytes.as_slice());
            let _ = write!(out, "{{\"$b\":{n}}}");
        }
    }
    Ok(())
}

/// Serialize a JSON number. Integral values within the exact-integer range
/// print without a decimal point (matching `JSON.stringify`), so the golden
/// vectors are byte-stable; other finite values fall back to `core`'s float
/// formatter. `-0.0` prints as `0`.
fn write_num(out: &mut String, n: f64) {
    // Integral within the exact-int range iff round-tripping through i64 is
    // lossless (avoids `f64::fract`/`abs`, which are std-only).
    if n == 0.0 {
        out.push('0');
    } else if n.is_finite()
        && n > -MAX_SAFE_INT_F64
        && n < MAX_SAFE_INT_F64
        && n == (n as i64) as f64
    {
        let _ = write!(out, "{}", n as i64);
    } else {
        let _ = write!(out, "{n}");
    }
}

/// Decode an RBS1 return into a [`Value`], reviving each `{"$b":N}` sentinel
/// back into [`Value::Bytes`] from segment `N`. `Err(Reason::BadMagic)` signals
/// the buffer is a plain-JSON reply (the caller parses it directly).
pub fn decode_value(buf: &[u8]) -> Result<Value, Reason> {
    let decoded = decode_envelope(buf)?;
    let json_str = core::str::from_utf8(decoded.json).map_err(|_| Reason::BadJson)?;
    let parsed = parse_json(json_str).map_err(|_| Reason::BadJson)?;
    revive(parsed, &decoded.segments)
}

/// Decode a host REPLY that may be EITHER an RBS1 envelope (byte streams
/// revived into [`Value::Bytes`]) OR a plain-JSON body with no segments (the
/// back-compat path — e.g. a `{"version":n}` ack or a bare `null`). Returns the
/// parsed [`Value`] in both cases, so an SDK wrapper can read a reply without
/// first knowing whether it carried bytes.
///
/// A leading u32 that is not the RBS1 magic is NOT an error here: it means the
/// body is plain JSON, so it is parsed directly (`BadMagic` is swallowed). Any
/// OTHER reason (a malformed frame that DID claim the magic) is surfaced.
pub fn decode_reply(buf: &[u8]) -> Result<Value, Reason> {
    match decode_value(buf) {
        Ok(value) => Ok(value),
        Err(Reason::BadMagic) => {
            let s = core::str::from_utf8(buf).map_err(|_| Reason::BadJson)?;
            parse_json(s).map_err(|_| Reason::BadJson)
        }
        Err(other) => Err(other),
    }
}

/// Replace every `{"$b":N}` sentinel object in `value` with `Bytes(segments[N])`.
fn revive(value: Value, segments: &[&[u8]]) -> Result<Value, Reason> {
    match value {
        Value::Obj(entries) => {
            // Any object carrying the reserved key `$b` MUST be exactly
            // `{"$b": <non-negative integer>}`; anything else is a malformed
            // sentinel (fail-closed) rather than literal application data.
            if entries.iter().any(|(k, _)| k == "$b") {
                if entries.len() != 1 {
                    return Err(Reason::BadSentinel);
                }
                let n = match &entries[0].1 {
                    // A non-negative integer, checked without `f64::fract`: an
                    // out-of-range or fractional value fails the lossless
                    // round-trip through usize.
                    Value::Num(n)
                        if *n >= 0.0 && *n < MAX_SAFE_INT_F64 && *n == (*n as usize) as f64 =>
                    {
                        *n as usize
                    }
                    _ => return Err(Reason::BadSentinel),
                };
                let seg = segments.get(n).ok_or(Reason::BadSegmentRef)?;
                return Ok(Value::Bytes(seg.to_vec()));
            }
            let mut out = Vec::with_capacity(entries.len());
            for (k, v) in entries {
                out.push((k, revive(v, segments)?));
            }
            Ok(Value::Obj(out))
        }
        Value::Arr(items) => {
            let mut out = Vec::with_capacity(items.len());
            for it in items {
                out.push(revive(it, segments)?);
            }
            Ok(Value::Arr(out))
        }
        other => Ok(other),
    }
}

// ---- minimal no_std JSON parser (control plane -> Value; no Bytes variant) ----
//
// A pared-down sibling of `mini_json.rs` (which is std-only, for build.rs +
// conformance): same strict grammar, but `no_std` (alloc) and a unit error the
// codec maps to `Reason::BadJson`. Input is `&str`, so string byte boundaries
// are valid.

fn parse_json(src: &str) -> Result<Value, ()> {
    let bytes = src.as_bytes();
    let mut pos = 0usize;
    let value = parse_value(bytes, &mut pos)?;
    skip_ws(bytes, &mut pos);
    if pos != bytes.len() {
        return Err(());
    }
    Ok(value)
}

fn skip_ws(bytes: &[u8], pos: &mut usize) {
    while let Some(b) = bytes.get(*pos) {
        match b {
            b' ' | b'\t' | b'\n' | b'\r' => *pos += 1,
            _ => break,
        }
    }
}

fn parse_value(bytes: &[u8], pos: &mut usize) -> Result<Value, ()> {
    skip_ws(bytes, pos);
    match bytes.get(*pos) {
        Some(b'{') => parse_object(bytes, pos),
        Some(b'[') => parse_array(bytes, pos),
        Some(b'"') => Ok(Value::Str(parse_string(bytes, pos)?)),
        Some(b't') => parse_lit(bytes, pos, b"true", Value::Bool(true)),
        Some(b'f') => parse_lit(bytes, pos, b"false", Value::Bool(false)),
        Some(b'n') => parse_lit(bytes, pos, b"null", Value::Null),
        Some(b'-') | Some(b'0'..=b'9') => parse_number(bytes, pos),
        _ => Err(()),
    }
}

fn parse_lit(bytes: &[u8], pos: &mut usize, lit: &[u8], value: Value) -> Result<Value, ()> {
    if bytes.len() >= *pos + lit.len() && &bytes[*pos..*pos + lit.len()] == lit {
        *pos += lit.len();
        Ok(value)
    } else {
        Err(())
    }
}

fn parse_object(bytes: &[u8], pos: &mut usize) -> Result<Value, ()> {
    *pos += 1; // '{'
    let mut entries = Vec::new();
    skip_ws(bytes, pos);
    if bytes.get(*pos) == Some(&b'}') {
        *pos += 1;
        return Ok(Value::Obj(entries));
    }
    loop {
        skip_ws(bytes, pos);
        if bytes.get(*pos) != Some(&b'"') {
            return Err(());
        }
        let key = parse_string(bytes, pos)?;
        skip_ws(bytes, pos);
        if bytes.get(*pos) != Some(&b':') {
            return Err(());
        }
        *pos += 1;
        let value = parse_value(bytes, pos)?;
        entries.push((key, value));
        skip_ws(bytes, pos);
        match bytes.get(*pos) {
            Some(b',') => *pos += 1,
            Some(b'}') => {
                *pos += 1;
                return Ok(Value::Obj(entries));
            }
            _ => return Err(()),
        }
    }
}

fn parse_array(bytes: &[u8], pos: &mut usize) -> Result<Value, ()> {
    *pos += 1; // '['
    let mut items = Vec::new();
    skip_ws(bytes, pos);
    if bytes.get(*pos) == Some(&b']') {
        *pos += 1;
        return Ok(Value::Arr(items));
    }
    loop {
        items.push(parse_value(bytes, pos)?);
        skip_ws(bytes, pos);
        match bytes.get(*pos) {
            Some(b',') => *pos += 1,
            Some(b']') => {
                *pos += 1;
                return Ok(Value::Arr(items));
            }
            _ => return Err(()),
        }
    }
}

fn parse_string(bytes: &[u8], pos: &mut usize) -> Result<String, ()> {
    *pos += 1; // opening quote
    let mut out = String::new();
    loop {
        match bytes.get(*pos) {
            None => return Err(()),
            Some(b'"') => {
                *pos += 1;
                return Ok(out);
            }
            Some(b'\\') => {
                *pos += 1;
                match bytes.get(*pos) {
                    Some(b'"') => out.push('"'),
                    Some(b'\\') => out.push('\\'),
                    Some(b'/') => out.push('/'),
                    Some(b'b') => out.push('\u{8}'),
                    Some(b'f') => out.push('\u{c}'),
                    Some(b'n') => out.push('\n'),
                    Some(b'r') => out.push('\r'),
                    Some(b't') => out.push('\t'),
                    Some(b'u') => {
                        let hi = parse_hex4(bytes, *pos + 1)?;
                        *pos += 4;
                        let ch = if (0xd800..0xdc00).contains(&hi) {
                            if bytes.get(*pos + 1) != Some(&b'\\')
                                || bytes.get(*pos + 2) != Some(&b'u')
                            {
                                return Err(());
                            }
                            let lo = parse_hex4(bytes, *pos + 3)?;
                            *pos += 6;
                            if !(0xdc00..0xe000).contains(&lo) {
                                return Err(());
                            }
                            0x10000 + ((hi - 0xd800) << 10) + (lo - 0xdc00)
                        } else if (0xdc00..0xe000).contains(&hi) {
                            return Err(());
                        } else {
                            hi
                        };
                        out.push(char::from_u32(ch).ok_or(())?);
                    }
                    _ => return Err(()),
                }
                *pos += 1;
            }
            Some(&b) if b < 0x20 => return Err(()),
            Some(_) => {
                let start = *pos;
                *pos += 1;
                while bytes.get(*pos).is_some_and(|b| b & 0xc0 == 0x80) {
                    *pos += 1;
                }
                out.push_str(core::str::from_utf8(&bytes[start..*pos]).map_err(|_| ())?);
            }
        }
    }
}

fn parse_hex4(bytes: &[u8], at: usize) -> Result<u32, ()> {
    if bytes.len() < at + 4 {
        return Err(());
    }
    let mut v = 0u32;
    for &b in &bytes[at..at + 4] {
        let d = match b {
            b'0'..=b'9' => (b - b'0') as u32,
            b'a'..=b'f' => (b - b'a' + 10) as u32,
            b'A'..=b'F' => (b - b'A' + 10) as u32,
            _ => return Err(()),
        };
        v = (v << 4) | d;
    }
    Ok(v)
}

fn parse_number(bytes: &[u8], pos: &mut usize) -> Result<Value, ()> {
    let start = *pos;
    if bytes.get(*pos) == Some(&b'-') {
        *pos += 1;
    }
    while bytes
        .get(*pos)
        .is_some_and(|b| b.is_ascii_digit() || matches!(b, b'.' | b'e' | b'E' | b'+' | b'-'))
    {
        *pos += 1;
    }
    let text = core::str::from_utf8(&bytes[start..*pos]).map_err(|_| ())?;
    text.parse::<f64>().map(Value::Num).map_err(|_| ())
}

#[cfg(test)]
#[path = "store_net_encode_tests.rs"]
mod tests;
