//! Generate the gpu budget constants + host-preset pipeline ids from
//! `contracts/graphics-seams.json` — the repo's SINGLE authoritative source for
//! the graphics seam contracts (see that file's top-level `$comment`).
//!
//! Generating (instead of hand-copying) makes drift STRUCTURALLY impossible on
//! the Rust side: the constants in `gpu::` are whatever the contract says, and
//! a missing/renamed contract key fails the build loudly right here. The wire
//! SHAPES (op names + field names), which live in hand-written `format!`
//! strings, are locked to the same file by the conformance tests
//! (`src/conformance.rs`).
//!
//! The generated file contains only `pub const` items and a tiny `pub mod` —
//! plain source with zero dependencies, so the `no_std` + wasm32 target of the
//! crate itself is untouched (build scripts always run on the build host).

use std::env;
use std::fs;
use std::path::Path;

// The shared minimal JSON parser (also used by the conformance tests). A build
// script cannot depend on its own crate, so pull the file in textually.
include!("src/mini_json.rs");

/// (contract key, Rust const name, Rust type, doc comment)
const BUDGET_CONSTS: &[(&str, &str, &str, &str)] = &[
    (
        "maxCmds",
        "MAX_CMDS",
        "usize",
        "Max ops (any opcode) in one command buffer.",
    ),
    (
        "maxDrawCalls",
        "MAX_DRAW_CALLS",
        "usize",
        "Max DRAW*/draw-call ops in one submit.",
    ),
    (
        "maxPrimitives",
        "MAX_PRIMITIVES",
        "u64",
        "Max total primitives (triangles) summed over the submit.",
    ),
    (
        "maxInstancesPerDraw",
        "MAX_INSTANCES_PER_DRAW",
        "u32",
        "Max instances in a single DRAW_INSTANCED.",
    ),
    (
        "maxInstancesTotal",
        "MAX_INSTANCES_TOTAL",
        "u64",
        "Max instances summed over the submit.",
    ),
    (
        "maxElementsPerDraw",
        "MAX_ELEMENTS_PER_DRAW",
        "u32",
        "Max index/vertex count in a single draw.",
    ),
    (
        "maxPixels",
        "MAX_PIXELS",
        "u64",
        "Max estimated SHADED pixels (fill-rate proxy = Σ viewport_area × primitives).",
    ),
    (
        "maxBufferBytes",
        "MAX_BUFFER_BYTES",
        "usize",
        "Max bytes for one uploaded vertex/index buffer.",
    ),
];

fn main() {
    let manifest_dir = env::var("CARGO_MANIFEST_DIR").expect("CARGO_MANIFEST_DIR");
    let contract_path = Path::new(&manifest_dir).join("../../contracts/graphics-seams.json");
    // Emitting any rerun-if-changed replaces cargo's "any file" default, so
    // list EVERY input: the contract and the include!d parser (build.rs itself
    // is always tracked).
    println!("cargo:rerun-if-changed={}", contract_path.display());
    println!(
        "cargo:rerun-if-changed={}",
        Path::new(&manifest_dir).join("src/mini_json.rs").display()
    );

    let src = fs::read_to_string(&contract_path)
        .unwrap_or_else(|e| panic!("read {}: {e}", contract_path.display()));
    let root =
        Json::parse(&src).unwrap_or_else(|e| panic!("parse {}: {e}", contract_path.display()));
    let gpu = root
        .get("seams")
        .and_then(|s| s.get("host:gpu"))
        .expect("contract: seams['host:gpu'] missing");
    let budget = gpu
        .get("budget")
        .expect("contract: host:gpu.budget missing");
    let presets = gpu
        .get("presets")
        .expect("contract: host:gpu.presets missing");

    let mut out = String::from(
        "// @generated by crates/rill-guest/build.rs from contracts/graphics-seams.json.\n\
         // Do not edit; change the contract instead (it is the single source of truth\n\
         // for this SDK AND the downstream host validators).\n\n",
    );

    out.push_str("// ---- per-submit COST BUDGET (host recomputes + enforces; fail-closed) ----\n");
    for (key, name, ty, doc) in BUDGET_CONSTS {
        let value = budget.get(key).and_then(Json::as_u64).unwrap_or_else(|| {
            panic!("contract: host:gpu.budget.{key} missing or not a non-negative integer")
        });
        out.push_str(&format!("/// {doc}\npub const {name}: {ty} = {value};\n"));
    }

    out.push_str(
        "\n/// HOST-PRESET pipeline ids. In \u{2462}-a the guest CANNOT author shaders; it picks\n\
         /// one of these fixed, host-compiled pipelines by integer id. Adding a preset\n\
         /// is a HOST change (audited), never a guest capability.\n\
         pub mod preset {\n",
    );
    let entries = presets
        .entries()
        .expect("contract: host:gpu.presets must be an object");
    let mut emitted = 0usize;
    for (name, spec) in entries {
        if name.starts_with('$') {
            continue; // $comment
        }
        let id = spec
            .get("id")
            .and_then(Json::as_u64)
            .unwrap_or_else(|| panic!("contract: host:gpu.presets.{name}.id missing"));
        let doc = spec
            .get("description")
            .and_then(Json::as_str)
            .unwrap_or_else(|| panic!("contract: host:gpu.presets.{name}.description missing"));
        for line in doc.split('\n') {
            out.push_str(&format!("    /// {line}\n"));
        }
        out.push_str(&format!("    pub const {name}: u32 = {id};\n"));
        emitted += 1;
    }
    assert!(emitted > 0, "contract: host:gpu.presets is empty");
    out.push_str("}\n");

    let out_dir = env::var("OUT_DIR").expect("OUT_DIR");
    let out_path = Path::new(&out_dir).join("graphics_contract.rs");
    fs::write(&out_path, out).unwrap_or_else(|e| panic!("write {}: {e}", out_path.display()));
}
