//! Generate the gpu budget constants + host-preset pipeline ids from
//! `contracts/graphics-seams.json` — the repo's SINGLE authoritative source for
//! the graphics seam contracts (see that file's top-level `$comment`).
//!
//! Generating (instead of hand-copying) makes drift STRUCTURALLY impossible on
//! the Rust side: the constants in `gpu::` are whatever the contract says, and
//! a missing/renamed contract key fails the build loudly right here. The wire
//! SHAPES (op names + field names), which live in hand-written `format!`
//! strings, are locked to the same file by the conformance tests
//! (`src/conformance.rs`).
//!
//! The generated file contains only `pub const` items and a tiny `pub mod` —
//! plain source with zero dependencies, so the `no_std` + wasm32 target of the
//! crate itself is untouched (build scripts always run on the build host).

use std::env;
use std::fs;
use std::path::Path;

// The shared minimal JSON parser (also used by the conformance tests). A build
// script cannot depend on its own crate, so pull the file in textually.
include!("src/mini_json.rs");

/// (contract key, Rust const name, Rust type, doc comment)
const BUDGET_CONSTS: &[(&str, &str, &str, &str)] = &[
    (
        "maxCmds",
        "MAX_CMDS",
        "usize",
        "Max ops (any opcode) in one command buffer.",
    ),
    (
        "maxDrawCalls",
        "MAX_DRAW_CALLS",
        "usize",
        "Max DRAW*/draw-call ops in one submit.",
    ),
    (
        "maxPrimitives",
        "MAX_PRIMITIVES",
        "u64",
        "Max total primitives (triangles) summed over the submit.",
    ),
    (
        "maxInstancesPerDraw",
        "MAX_INSTANCES_PER_DRAW",
        "u32",
        "Max instances in a single DRAW_INSTANCED.",
    ),
    (
        "maxInstancesTotal",
        "MAX_INSTANCES_TOTAL",
        "u64",
        "Max instances summed over the submit.",
    ),
    (
        "maxElementsPerDraw",
        "MAX_ELEMENTS_PER_DRAW",
        "u32",
        "Max index/vertex count in a single draw.",
    ),
    (
        "maxPixels",
        "MAX_PIXELS",
        "u64",
        "Max estimated SHADED pixels (fill-rate proxy = Σ viewport_area × primitives).",
    ),
    (
        "maxBufferBytes",
        "MAX_BUFFER_BYTES",
        "usize",
        "Max bytes for one uploaded vertex/index buffer.",
    ),
];

fn main() {
    let manifest_dir = env::var("CARGO_MANIFEST_DIR").expect("CARGO_MANIFEST_DIR");
    let contract_path = Path::new(&manifest_dir).join("../../contracts/graphics-seams.json");
    // Emitting any rerun-if-changed replaces cargo's "any file" default, so
    // list EVERY input: the contract and the include!d parser (build.rs itself
    // is always tracked).
    println!("cargo:rerun-if-changed={}", contract_path.display());
    println!(
        "cargo:rerun-if-changed={}",
        Path::new(&manifest_dir).join("src/mini_json.rs").display()
    );

    let src = fs::read_to_string(&contract_path)
        .unwrap_or_else(|e| panic!("read {}: {e}", contract_path.display()));
    let root =
        Json::parse(&src).unwrap_or_else(|e| panic!("parse {}: {e}", contract_path.display()));
    let gpu = root
        .get("seams")
        .and_then(|s| s.get("host:gpu"))
        .expect("contract: seams['host:gpu'] missing");
    let budget = gpu
        .get("budget")
        .expect("contract: host:gpu.budget missing");
    let presets = gpu
        .get("presets")
        .expect("contract: host:gpu.presets missing");

    let mut out = String::from(
        "// @generated by crates/rill-guest/build.rs from contracts/graphics-seams.json.\n\
         // Do not edit; change the contract instead (it is the single source of truth\n\
         // for this SDK AND the downstream host validators).\n\n",
    );

    out.push_str("// ---- per-submit COST BUDGET (host recomputes + enforces; fail-closed) ----\n");
    for (key, name, ty, doc) in BUDGET_CONSTS {
        let value = budget.get(key).and_then(Json::as_u64).unwrap_or_else(|| {
            panic!("contract: host:gpu.budget.{key} missing or not a non-negative integer")
        });
        out.push_str(&format!("/// {doc}\npub const {name}: {ty} = {value};\n"));
    }

    out.push_str(
        "\n/// HOST-PRESET pipeline ids. In \u{2462}-a the guest CANNOT author shaders; it picks\n\
         /// one of these fixed, host-compiled pipelines by integer id. Adding a preset\n\
         /// is a HOST change (audited), never a guest capability.\n\
         pub mod preset {\n",
    );
    let entries = presets
        .entries()
        .expect("contract: host:gpu.presets must be an object");
    let mut emitted = 0usize;
    for (name, spec) in entries {
        if name.starts_with('$') {
            continue; // $comment
        }
        let id = spec
            .get("id")
            .and_then(Json::as_u64)
            .unwrap_or_else(|| panic!("contract: host:gpu.presets.{name}.id missing"));
        let doc = spec
            .get("description")
            .and_then(Json::as_str)
            .unwrap_or_else(|| panic!("contract: host:gpu.presets.{name}.description missing"));
        for line in doc.split('\n') {
            out.push_str(&format!("    /// {line}\n"));
        }
        out.push_str(&format!("    pub const {name}: u32 = {id};\n"));
        emitted += 1;
    }
    assert!(emitted > 0, "contract: host:gpu.presets is empty");
    out.push_str("}\n");

    let out_dir = env::var("OUT_DIR").expect("OUT_DIR");
    let out_path = Path::new(&out_dir).join("graphics_contract.rs");
    fs::write(&out_path, out).unwrap_or_else(|e| panic!("write {}: {e}", out_path.display()));

    generate_op_batch_contract(&manifest_dir, &out_dir);
}

/// Convert a camelCase contract key (e.g. `maxOps`) to a SCREAMING_SNAKE Rust
/// const name (`MAX_OPS`). Keys that are already SCREAMING_SNAKE
/// (`BOOL_FALSE`, `CREATE`) pass through unchanged.
fn screaming_snake(key: &str) -> String {
    let mut out = String::new();
    let mut prev: Option<char> = None;
    for ch in key.chars() {
        // Insert a separator only on a lower/digit -> upper boundary, judged on
        // the ORIGINAL characters, so `maxOps` -> `MAX_OPS` while an already
        // SCREAMING_SNAKE name (`BOOL_FALSE`) passes through unchanged.
        if ch.is_ascii_uppercase()
            && matches!(prev, Some(p) if p.is_ascii_lowercase() || p.is_ascii_digit())
        {
            out.push('_');
        }
        out.push(ch.to_ascii_uppercase());
        prev = Some(ch);
    }
    out
}

/// Emit the u8 constants of a flat `name -> integer` contract object (opcodes,
/// valueTags, batchFlags) into `pub mod <mod_name>`. `$`-prefixed keys
/// (`$comment`) are skipped.
fn emit_u8_enum(out: &mut String, node: &Json, mod_name: &str, doc: &str) {
    out.push_str(&format!("/// {doc}\npub mod {mod_name} {{\n"));
    let entries = node
        .entries()
        .unwrap_or_else(|| panic!("contract: {mod_name} must be an object"));
    let mut emitted = 0usize;
    for (name, val) in entries {
        if name.starts_with('$') {
            continue;
        }
        let n = val
            .as_u64()
            .unwrap_or_else(|| panic!("contract: {mod_name}.{name} not a non-negative integer"));
        out.push_str(&format!(
            "    pub const {}: u8 = {n};\n",
            screaming_snake(name)
        ));
        emitted += 1;
    }
    assert!(emitted > 0, "contract: {mod_name} is empty");
    out.push_str("}\n");
}

/// Generate `op_batch_contract.rs` (opcode / value-tag / flag / limit
/// constants, magic, protocol version) from `contracts/op-batch-wire.json`,
/// the single authoritative source for the guest->host binary wire protocol.
/// Same rationale as the graphics generator: the Rust codec's magic bytes,
/// tag numbers and fail-closed caps are whatever the contract says, so they
/// cannot drift, and a renamed/removed key fails the build here.
fn generate_op_batch_contract(manifest_dir: &str, out_dir: &str) {
    let contract_path = Path::new(manifest_dir).join("../../contracts/op-batch-wire.json");
    println!("cargo:rerun-if-changed={}", contract_path.display());

    let src = fs::read_to_string(&contract_path)
        .unwrap_or_else(|e| panic!("read {}: {e}", contract_path.display()));
    let root =
        Json::parse(&src).unwrap_or_else(|e| panic!("parse {}: {e}", contract_path.display()));

    let mut out = String::from(
        "// @generated by crates/rill-guest/build.rs from contracts/op-batch-wire.json.\n\
         // Do not edit; change the contract instead (it is the single source of truth\n\
         // for this codec AND the TS encoder/decoder + host validators).\n\n",
    );

    // Derive MAGIC from the contract's `hex` field, NOT its `u32le` decimal.
    // The decimal (1280592210 = 0x4C544952) is an upstream typo: its LE bytes
    // are 52 49 54 4C = 'RITL'. The `hex` (0x4c4c4952), `asciiBytes`
    // (52 49 4C 4C) and EVERY golden vector agree on 'RILL' = 0x4c4c4952 =
    // 1280067922, so `hex` is the value consistent with the oracle. We
    // additionally verify `hex`'s LE bytes spell the ASCII string in
    // `asciiBytes` so a future edit to either field fails the build loudly.
    let magic_node = root.get("magic").expect("contract: magic missing");
    let magic_hex = magic_node
        .get("hex")
        .and_then(Json::as_str)
        .expect("contract: magic.hex missing");
    let magic = u32::from_str_radix(magic_hex.trim_start_matches("0x"), 16)
        .unwrap_or_else(|e| panic!("contract: magic.hex {magic_hex:?} not hex: {e}"));
    let ascii = magic_node
        .get("asciiBytes")
        .and_then(Json::as_str)
        .expect("contract: magic.asciiBytes missing");
    let ascii_from_hex: String = magic
        .to_le_bytes()
        .iter()
        .map(|b| format!("{b:02X}"))
        .collect::<Vec<_>>()
        .join(" ");
    assert_eq!(
        ascii_from_hex, ascii,
        "contract: magic.hex LE bytes disagree with magic.asciiBytes"
    );
    out.push_str(&format!(
        "/// First 4 bytes of every batch, read as a u32 LE ('RILL'). Reject on mismatch.\n\
         /// Derived from contract `magic.hex` ({magic_hex}); the contract's `u32le`\n\
         /// decimal is a known upstream typo (spells 'RITL') and is NOT used.\n\
         pub const MAGIC: u32 = {magic};\n"
    ));

    let version = root
        .get("protocolVersion")
        .and_then(|v| v.get("value"))
        .and_then(Json::as_u64)
        .expect("contract: protocolVersion.value missing");
    out.push_str(&format!(
        "/// Protocol version written after the magic (u16). This codec speaks v1 only.\n\
         pub const PROTOCOL_VERSION: u16 = {version};\n\n"
    ));

    emit_u8_enum(
        &mut out,
        root.get("opcodes").expect("contract: opcodes missing"),
        "opcode",
        "u8 tag leading every operation record.",
    );
    out.push('\n');
    emit_u8_enum(
        &mut out,
        root.get("valueTags").expect("contract: valueTags missing"),
        "tag",
        "u8 tag leading every encoded SerializedValue.",
    );
    out.push('\n');
    emit_u8_enum(
        &mut out,
        root.get("batchFlags")
            .expect("contract: batchFlags missing"),
        "flags",
        "Bitmask values OR'd into header.flags (v1 default is NONE).",
    );
    out.push('\n');

    out.push_str(
        "/// Fail-closed structural caps (mostly u16 field widths). On any breach the\n\
         /// encoder aborts the whole batch and emits nothing.\n\
         pub mod limits {\n",
    );
    let limits = root.get("limits").expect("contract: limits missing");
    let entries = limits
        .entries()
        .expect("contract: limits must be an object");
    let mut emitted = 0usize;
    for (name, spec) in entries {
        if name.starts_with('$') {
            continue;
        }
        let value = spec
            .get("value")
            .and_then(Json::as_u64)
            .unwrap_or_else(|| panic!("contract: limits.{name}.value missing"));
        out.push_str(&format!(
            "    pub const {}: usize = {value};\n",
            screaming_snake(name)
        ));
        emitted += 1;
    }
    assert!(emitted > 0, "contract: limits is empty");
    out.push_str("}\n");

    let out_path = Path::new(out_dir).join("op_batch_contract.rs");
    fs::write(&out_path, out).unwrap_or_else(|e| panic!("write {}: {e}", out_path.display()));
}
